// Code Generated by Sidekick is for learning and experimentation purposes only.
import 'package:flutter/material.dart';
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';

void main() {
  runApp(const CropDoctorApp());
}

class CropDoctorApp extends StatelessWidget {
  const CropDoctorApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Crop Doctor',
      theme: ThemeData(primarySwatch: Colors.green),
      home:
          const LoginScreen(), // This now uses the one from screens/login_screen.dart
    );
  }
}
